spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.1bd0666304ac4da7
            client-secret: a270bf182f0c4bb925f8f21524365472f7f3e4a4

  data:
    cassandra:
      keyspace-name: main
      username: HAgOUvjeGljjLPNQpdhTYuvH
      password: k6Kj9xhA3yK7HKEb3.uBG01akG9ZYR7.ZKxdHo5oU0Cx2iS7Izg,gk6jYjPQWm7stiYp962Ged+iAzWK86toh.LwwsWx5cnrhvsKxBp2bBnjZkdjPswBZ1hE,3L8rXKL
      schema-action: create-if-not-exists
      request: 
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

  application:
    name: betterReads

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: e4af7894-f822-4e6c-92f9-b632367d2858
  region: asia-south1
  keyspace: main
  application.token: AstraCS:HAgOUvjeGljjLPNQpdhTYuvH:e4dff2ee653bc407c50af695a2c6c0737e20c29b165f5695174928a05b93b48e